### ISSUE TITLE
dtplyr 1.0.0

### ISSUE THREAD

**Issue by hadley** [ModelOriented/randomForestExplainer#12]
This is a heads up to let you know that I'm planning to release [dtplyr 1.0.0](https://dtplyr.tidyverse.org) in the near future. This is a complete rewrite of dtplyr so it generates vastly more performant data.table code, but it did require a complete rework of the API so your existing dtplyr code is unlikely to continue to work.

**Comment by hadley** [comment]
To be more concrete, you'll now need to explicitly start dplyr pipelines with `lazy_dt()` and explicitly force computation with `as.data.table()`/`as.data.frame()`/`as_tibble()`.

I think it should be a fairly simple change to your code, but please let me know if there's anything I can do to help.

**Comment by Yue-Jiang** [comment]
Thanks for the note @hadley! Actually I wasn't able to find the function that actually imports dtplyr, so I suspect it might have been in the `Imports` field just because of historical reasons. @pbiecek @OlaPaluszynska If either of you could confirm, I'm going to remove dtplyr from `Imports`. I've tested it locally and nothing seems affected.

**Comment by pbiecek** [comment]
@Yue-Jiang yes it's likely that's a dependency from some early version of randomForestExplainer.
Would you check if other packages from the DESCRIPTION are still needed there?
